package io.github.lessmade.gothdb.core.service;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.List;

import io.github.lessmade.gothdb.core.exception.SchemaNotFoundException;
import io.github.lessmade.gothdb.core.exception.TableNotFoundException;
import io.github.lessmade.gothdb.core.model.ColumnInfo;
import io.github.lessmade.gothdb.core.model.ForeignKeyInfo;
import io.github.lessmade.gothdb.core.model.IndexInfo;
import io.github.lessmade.gothdb.core.model.PrimaryKeyInfo;
import io.github.lessmade.gothdb.core.model.RowPage;
import io.github.lessmade.gothdb.core.model.SchemaInfo;
import io.github.lessmade.gothdb.core.model.TableInfo;
import io.github.lessmade.gothdb.core.schema.PatternSchemaFilter;
import io.github.lessmade.gothdb.core.value.DefaultJdbcValueConverter;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class DatabaseMetadataServiceTests {

    private DatabaseMetadataService metadataService;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:metadata;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");

        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement()) {
            statement.execute("DROP SCHEMA IF EXISTS APP CASCADE");
            statement.execute("CREATE SCHEMA APP");
            statement.execute("""
                    CREATE TABLE APP.CUSTOMER (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NAME VARCHAR(100) NOT NULL,
                        CREDIT DECIMAL(10, 2),
                        NICKNAME VARCHAR(40) DEFAULT 'anonymous'
                    )
                    """);
            statement.execute("CREATE VIEW APP.CUSTOMER_NAMES AS SELECT ID, NAME FROM APP.CUSTOMER");
            statement.execute("""
                    CREATE TABLE APP.ORDERS (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        CUSTOMER_ID BIGINT NOT NULL,
                        CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES APP.CUSTOMER (ID)
                    )
                    """);
            statement.execute("CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON APP.ORDERS (CUSTOMER_ID)");
            statement.execute("""
                    INSERT INTO APP.CUSTOMER (NAME, CREDIT) VALUES
                        ('Alice', 100.00),
                        ('Bob', 200.00),
                        ('Carol', 300.00)
                    """);
        }

        metadataService = new DatabaseMetadataService(dataSource);
    }

    @Test
    void readsSchemas() {
        assertThat(metadataService.getSchemas())
                .extracting(SchemaInfo::name)
                .contains("APP");
    }

    @Test
    void readsTablesAndViews() {
        assertThat(metadataService.getTables("APP"))
                .extracting(TableInfo::name, TableInfo::type)
                .contains(
                        assertThatTuple("CUSTOMER", "BASE TABLE"),
                        assertThatTuple("CUSTOMER_NAMES", "VIEW"));
    }

    @Test
    void readsColumnsInOrdinalOrder() {
        List<ColumnInfo> columns = metadataService.getColumns("APP", "CUSTOMER");

        assertThat(columns)
                .extracting(ColumnInfo::name)
                .containsExactly("ID", "NAME", "CREDIT", "NICKNAME");
        assertThat(columns.get(0).autoIncrement()).isTrue();
        assertThat(columns.get(1).nullable()).isFalse();
        assertThat(columns.get(1).jdbcType()).isEqualTo(Types.VARCHAR);
        assertThat(columns.get(2).size()).isEqualTo(10);
        assertThat(columns.get(2).scale()).isEqualTo(2);
        assertThat(columns.get(3).defaultValue()).contains("anonymous");
    }

    @Test
    void treatsWildcardCharactersAsLiteralNames() {
        assertThatThrownBy(() -> metadataService.getTables("APP%"))
                .isInstanceOf(SchemaNotFoundException.class);
        assertThatThrownBy(() -> metadataService.getColumns("APP", "CUSTOMER%"))
                .isInstanceOf(TableNotFoundException.class);
    }

    @Test
    void throwsWhenSchemaIsMissing() {
        assertThatThrownBy(() -> metadataService.getTables("MISSING"))
                .isInstanceOf(SchemaNotFoundException.class)
                .hasMessage("Schema not found: MISSING");
        assertThatThrownBy(() -> metadataService.getColumns("MISSING", "CUSTOMER"))
                .isInstanceOf(SchemaNotFoundException.class);
    }

    @Test
    void hidesFilteredSchemasFromListingAndDirectAccess() {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:metadata;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        DatabaseMetadataService filteredService = new DatabaseMetadataService(
                dataSource,
                new DefaultJdbcValueConverter(),
                new PatternSchemaFilter(List.of(), List.of("APP")));

        assertThat(filteredService.getSchemas())
                .extracting(SchemaInfo::name)
                .doesNotContain("APP");
        assertThatThrownBy(() -> filteredService.getTables("APP"))
                .isInstanceOf(SchemaNotFoundException.class)
                .hasMessage("Schema not found: APP");
    }

    @Test
    void throwsWhenTableIsMissing() {
        assertThatThrownBy(() -> metadataService.getColumns("APP", "MISSING"))
                .isInstanceOf(TableNotFoundException.class)
                .hasMessage("Table not found: APP.MISSING");
    }

    @Test
    void readsPrimaryKey() {
        assertThat(metadataService.getPrimaryKeys("APP", "CUSTOMER"))
                .extracting(PrimaryKeyInfo::columnName, PrimaryKeyInfo::keySequence)
                .containsExactly(assertThatTuple("ID", 1));
    }

    @Test
    void readsForeignKeys() {
        assertThat(metadataService.getForeignKeys("APP", "ORDERS"))
                .extracting(
                        ForeignKeyInfo::columnName,
                        ForeignKeyInfo::referencedTable,
                        ForeignKeyInfo::referencedColumn)
                .containsExactly(assertThatTuple("CUSTOMER_ID", "CUSTOMER", "ID"));
    }

    @Test
    void returnsNoForeignKeysWhenTableHasNone() {
        assertThat(metadataService.getForeignKeys("APP", "CUSTOMER")).isEmpty();
    }

    @Test
    void readsIndexes() {
        assertThat(metadataService.getIndexes("APP", "ORDERS"))
                .extracting(IndexInfo::name, IndexInfo::columnName)
                .contains(assertThatTuple("IDX_ORDERS_CUSTOMER_ID", "CUSTOMER_ID"));
    }

    @Test
    void throwsNotFoundForMissingTableOnKeyMetadata() {
        assertThatThrownBy(() -> metadataService.getPrimaryKeys("APP", "MISSING"))
                .isInstanceOf(TableNotFoundException.class);
        assertThatThrownBy(() -> metadataService.getForeignKeys("APP", "MISSING"))
                .isInstanceOf(TableNotFoundException.class);
        assertThatThrownBy(() -> metadataService.getIndexes("APP", "MISSING"))
                .isInstanceOf(TableNotFoundException.class);
    }

    @Test
    void readsRowsInPrimaryKeyOrderWithTotalCount() {
        RowPage firstPage = metadataService.getRows("APP", "CUSTOMER", 0, 2);

        assertThat(firstPage.page()).isEqualTo(0);
        assertThat(firstPage.size()).isEqualTo(2);
        assertThat(firstPage.totalElements()).isEqualTo(3);
        assertThat(firstPage.rows()).extracting(row -> row.get("NAME"))
                .containsExactly("Alice", "Bob");

        RowPage secondPage = metadataService.getRows("APP", "CUSTOMER", 1, 2);
        assertThat(secondPage.rows()).extracting(row -> row.get("NAME"))
                .containsExactly("Carol");
    }

    @Test
    void rejectsInvalidPagination() {
        assertThatThrownBy(() -> metadataService.getRows("APP", "CUSTOMER", -1, 10))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("page must not be negative");
        assertThatThrownBy(() -> metadataService.getRows("APP", "CUSTOMER", 0, 0))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("size must be at least 1");
        assertThatThrownBy(() -> metadataService.getRows("APP", "CUSTOMER", 0, 501))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("size must not exceed 500");
    }

    @Test
    void throwsNotFoundForMissingTableOnRows() {
        assertThatThrownBy(() -> metadataService.getRows("APP", "MISSING", 0, 10))
                .isInstanceOf(TableNotFoundException.class);
    }

    @Test
    void rejectsBlankNames() {
        assertThatThrownBy(() -> metadataService.getTables(" "))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("schema must not be blank");
        assertThatThrownBy(() -> metadataService.getColumns("APP", ""))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("table must not be blank");
    }

    private static org.assertj.core.groups.Tuple assertThatTuple(Object... values) {
        return org.assertj.core.groups.Tuple.tuple(values);
    }
}
