package io.github.lessmade.gothdb.core.service;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.List;

import io.github.lessmade.gothdb.core.model.ColumnInfo;
import io.github.lessmade.gothdb.core.model.SchemaInfo;
import io.github.lessmade.gothdb.core.model.TableInfo;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class DatabaseMetadataServiceTests {

    private DatabaseMetadataService metadataService;

    @BeforeEach
    void setUp() throws SQLException {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:metadata;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");

        try (Connection connection = dataSource.getConnection();
                Statement statement = connection.createStatement()) {
            statement.execute("DROP SCHEMA IF EXISTS APP CASCADE");
            statement.execute("CREATE SCHEMA APP");
            statement.execute("""
                    CREATE TABLE APP.CUSTOMER (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NAME VARCHAR(100) NOT NULL,
                        CREDIT DECIMAL(10, 2),
                        NICKNAME VARCHAR(40) DEFAULT 'anonymous'
                    )
                    """);
            statement.execute("CREATE VIEW APP.CUSTOMER_NAMES AS SELECT ID, NAME FROM APP.CUSTOMER");
        }

        metadataService = new DatabaseMetadataService(dataSource);
    }

    @Test
    void readsSchemas() {
        assertThat(metadataService.getSchemas())
                .extracting(SchemaInfo::name)
                .contains("APP");
    }

    @Test
    void readsTablesAndViews() {
        assertThat(metadataService.getTables("APP"))
                .extracting(TableInfo::name, TableInfo::type)
                .contains(
                        assertThatTuple("CUSTOMER", "BASE TABLE"),
                        assertThatTuple("CUSTOMER_NAMES", "VIEW"));
    }

    @Test
    void readsColumnsInOrdinalOrder() {
        List<ColumnInfo> columns = metadataService.getColumns("APP", "CUSTOMER");

        assertThat(columns)
                .extracting(ColumnInfo::name)
                .containsExactly("ID", "NAME", "CREDIT", "NICKNAME");
        assertThat(columns.get(0).autoIncrement()).isTrue();
        assertThat(columns.get(1).nullable()).isFalse();
        assertThat(columns.get(1).jdbcType()).isEqualTo(Types.VARCHAR);
        assertThat(columns.get(2).size()).isEqualTo(10);
        assertThat(columns.get(2).scale()).isEqualTo(2);
        assertThat(columns.get(3).defaultValue()).contains("anonymous");
    }

    @Test
    void treatsWildcardCharactersAsLiteralNames() {
        assertThat(metadataService.getTables("APP%")).isEmpty();
        assertThat(metadataService.getColumns("APP", "CUSTOMER%")).isEmpty();
    }

    @Test
    void rejectsBlankNames() {
        assertThatThrownBy(() -> metadataService.getTables(" "))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("schema must not be blank");
        assertThatThrownBy(() -> metadataService.getColumns("APP", ""))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessage("table must not be blank");
    }

    private static org.assertj.core.groups.Tuple assertThatTuple(Object... values) {
        return org.assertj.core.groups.Tuple.tuple(values);
    }
}
