<project xmlns="http://maven.apache.org/POM/4.0.0">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.lessmade</groupId>
        <artifactId>gothdb-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>gothdb-spring-boot-starter</artifactId>

    <name>GothDB Spring Boot Starter</name>
    <description>Spring Boot starter for GothDB.</description>
    <url>https://github.com/lessmade/gothdb</url>

    <dependencies>

        <dependency>
            <groupId>io.github.lessmade</groupId>
            <artifactId>gothdb-core</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.lessmade</groupId>
            <artifactId>gothdb-autoconfigure</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

    </dependencies>

</project>
